### ISSUE TITLE
Clustering: Optimal k

### ISSUE THREAD

**Issue by bdiptesh** [bdiptesh/CodeLib#1]
**Is your feature request related to a problem? Please describe.**
A clustering module to cluster any given data (categorical/continuos/ordinal) and returns optimal clustering solution

**Describe the solution you'd like**
Compute optimal clustering solution using gap-statistic.

Methods:
1. First SE
1. Maximum Gap

**Expected input**
```python
df: pandas.DataFrame
x_var: List[str]
max_cluster: int
method: Union[str]
```

**Expected API**
```python
opt_k
```

**Acceptance criteria**

Integration tests:
- [x] Categorical variables only
- [x] Continuos variables only
- [x] Ordinal variables only
- [x] Combination of categorical/ordinal/continuos

**Tasks**

- [x] Define integration tests
- [x] First pass implementation of Gap statistic
- [x] Modular implementation
