### ISSUE TITLE
Traveling salesman problem

### ISSUE THREAD

**Issue by bdiptesh** [bdiptesh/CodeLib#6]
**Is your feature request related to a problem? Please describe.**
Travelling salesman problem

**Describe the solution you'd like**
Travelling salesman problem with both integer programming and heuristic.

Methods:
1. Optimization
1. Heuristic

**Expected input**
```python
df: pandas.DataFrame
method: Union[str]
param: Dict
```

**Expected API**
```python
solve
```

**Acceptance criteria**
- Integration tests

**Tasks**

- [x] Define integration tests
- [x] Document the formulations for both IP and Heuristics
- [x] First pass implementation of TSP
- [x] Modular implementation
