### ISSUE TITLE
Transportation problem

### ISSUE THREAD

**Issue by bdiptesh** [bdiptesh/CodeLib#7]
**Is your feature request related to a problem? Please describe.**
Transportation problem

**Describe the solution you'd like**
Transportation problem using integer programming.

**Expected input**
```python
df: pandas.DataFrame
method: Union[str]
param: Dict
```

**Expected API**
```python
solve
```

**Acceptance criteria**
- Integration tests

**Tasks**

- [x] Define integration tests
- [x] Document the formulations for IP
- [x] First pass implementation of TP
- [x] Modular implementation
